### ISSUE TITLE
Got an error when getting service state

### ISSUE THREAD

**Issue by yujunz** [groundnuty/k8s-wait-for#12]
```
./wait_for.sh service mongodb-replicaset
expr: syntax error
error: name cannot be provided when a selector is specified
```

**Comment by groundnuty** [comment]
The fact of the matter is, that I never once used the `service` argument after writing a first version of the script. Thanks for catching that.

**Comment by percenuage** [comment]
Hello, I have this issue when I want to set multiple service like : `./wait_for.sh service front internal` and one of the service are ready (eg, front). Do you have any ideas ?
