### ISSUE TITLE
[Question/New Feature] Can the script handle more than one job/service... ?

### ISSUE THREAD

**Issue by exodussystem** [groundnuty/k8s-wait-for#14]
Instead of multiple initContainers, can the script handle more than one job/service?
Etc., It will stop waiting when all jobs are done (even some failed and some succeeded)

args: [
              "job", "job-1",
              "job", "job-2",
              ...
          ]

**Comment by groundnuty** [comment]
No. I usually just prefer to have a dedicated init-container for every dependency my service is waiting for. Thanks to that I get a nice `Init 0/3` output as shown in the [README](https://github.com/groundnuty/k8s-wait-for#complex-deployment-use-case). 

As a consequence, one needs to launch **N** containers sequentially which ofc. makes the pod startup longer. If that starts to be a problem still I think it's better to try to speed up init-container startup time. 

That being said it's possible to accomplish that by using the `command` option:
```
command:
  - "/bin/sh"
  - "-c"
  - >
    wait_for.sh pod -lapp=develop-volume-gluster-krakow;
    wait_for.sh pod job develop-volume-s3-krakow-init;
```
it still will be sequential but in one contianer.

When running >1000 pods on a single master, 50 node k8s, each waiting actively (`k8s-wait-for` uses kubectl to ask for status) for the dependency pod to start I found that I was basically DDoS-ing the `kube-apiserver` pod, as a result, a single execution of `kubectl` by the script took more than a second. Allowing the script to parallelly wait for multiple conditions would just make the DDoS attack of the k8s larger when dealing with a large number of pods.
