### ISSUE TITLE
Add option

### ISSUE THREAD

**Issue by roeera** [groundnuty/k8s-wait-for#16]
Hi,

It will be very nice to add an option to wait until all pods are running / failed in a specific namespace.
something like:
wait_for.sh namespace my-namespace 

Tx,
Roee.

**Comment by groundnuty** [comment]
That's actually supported already, as all the options are passed to `kubect` directly. 

Example:
That's the output of the k8s-wait-for container running on the cluster trying to wait for flannel pods that are deployed in namespace `kube-system`:
```
/ # # Check the namespace the pod was created in:
/ # cat /run/secrets/kubernetes.io/serviceaccount/namespace && echo ""
r1902
/ # wait_for.sh pod -lapp=flannel
Waiting for pod -lapp=flannel...
Waiting for pod -lapp=flannel...
^C
/ # # No pods labeled -lapp=flannel in namespace r1902
/ # wait_for.sh pod -lapp=flannel -n kube-system
[2019-06-10 18:09:09] pod -lapp=flannel -n kube-system is ready.
```
