### ISSUE TITLE
Wait for job still waiting if one of the pods failed

### ISSUE THREAD

**Issue by dorsany** [groundnuty/k8s-wait-for#17]
Hi @groundnuty ,

Your wait for service is amazing, but I have a feature request that maybe you can help with.

Issue:
I have a use case which sometimes (depends on the server resources) my job will create a pod that will be failed, but using ```backoffLimit``` it will create a second pod that will run successfully.
The thing is that ```wait for job``` is waiting that all pods will be succeeded and not just the last pod for a job.

Expected behavior:
add the ability to wait for job with only the last pod success and not all of the pods.

How to reproduce:
1) create job with```backoffLimit: 1``` 
2) create pod with wait for job above
3) failed the first pod from the job above
4) check the wait for pod logs

**Comment by groundnuty** [comment]
@dorsany I think that this feature is already implemented since the release v1.2 please see the example [here](https://github.com/groundnuty/k8s-wait-for/commit/8fe55c688ac3b73017d0038b9804089660b3aae4#diff-04c6e90faac2675aa89e2176d2eec7d8R41-R42).

**Comment by dorsany** [comment]
Right thanks!
