### ISSUE TITLE
syntax error: unexpected "else" (expecting "}")`

### ISSUE THREAD

**Issue by theophileds** [groundnuty/k8s-wait-for#34]
I'm experiencing the following error when using the latest release v1.5

`/usr/local/bin/wait_for.sh: line 183: syntax error: unexpected "else" (expecting "}")`

I think that it is related to an unexpected fi instruction.
https://github.com/groundnuty/k8s-wait-for/blob/30e860bce6ad6f7a14f61e5e66257156b8d3d2e5/wait_for.sh#L182

**Comment by groundnuty** [comment]
thanks I will release v1.5.1 today

**Comment by groundnuty** [comment]
fixed with 1c9c1a6
