### ISSUE TITLE
Error from server (Forbidden): jobs.batch is forbidden: User system:serviceaccount:pronto-proxy:default cannot get resource jobs in API group batch in the namespace 

### ISSUE THREAD

**Issue by mszpulak** [groundnuty/k8s-wait-for#39]
When starting pod I got following error
Error from server (Forbidden): jobs.batch is forbidden: User system:serviceaccount:blabla:default cannot get resource jobs in API group batch in the namespace blabla

**Comment by maxtomczyk** [comment]
Hello, I just faced same issue. Can you share your solution (if you solved it of course)?
