### ISSUE TITLE
Wait for at least one pods to enter 'Ready' state

### ISSUE THREAD

**Issue by adiarbili** [groundnuty/k8s-wait-for#41]
I have a scenario in which I need to wait for **at least** one pod to be ready instead of **all**.

**Comment by klamas1** [comment]
RTFM

```
Wait for at least one pod in that job to have 'Succeeded' state, does not mind some 'Failed' ones:
wait_for.sh job-wr develop-volume-s3-krakow-init
```

**Comment by groundnuty** [comment]
closing :-)

**Comment by velichkoStoev** [comment]
I'm not sure `job-wr` is what the OP was looking for here, `pod-wr` seems like the desired solution. I can see it's available [here](https://github.com/groundnuty/k8s-wait-for/blob/master/wait_for.sh#L235), but I don't see `TREAT_ERRORS_AS_READY` being handled inside `get_pod_state`, only [inside](https://github.com/groundnuty/k8s-wait-for/blob/master/wait_for.sh#L181) `get_job_state`. So, is `pod-wr` actually working?

**Comment by groundnuty** [comment]
looking at this [commit](https://github.com/groundnuty/k8s-wait-for/commit/8110775279b465a33b95a5d18bdcbed6732cba1e) it might not. The project might benefit from some unit tests, tho they would probably be N times longer then the project code itself :-)

**Comment by velichkoStoev** [comment]
PR created, @groundnuty , please, take a look. :)

**Comment by groundnuty** [comment]
@velichkoStoev I'm closing the issue as it was merged and will be included in the next release. Thank you for your contribution!
