### ISSUE TITLE
[Question] Move to GitHub Container Registry (ghcr.io)?

### ISSUE THREAD

**Issue by andrewcole** [groundnuty/k8s-wait-for#46]
Love the tool, use it extensively.

Would you consider a move to hosting your images on ghcr.io instead of at Docker Hub? Docker Hub has some quite onerous pull limits nowadays.

**Comment by groundnuty** [comment]
That's a good idea. I will release a new version sometime this month and do that as part of that effort.

**Comment by groundnuty** [comment]
commits 1a60c4866db157fcf585bf66d2105357944e379b 1a60c4866db157fcf585bf66d2105357944e379b added ghcr support, please comment if it's enough

**Comment by tim-sendible** [comment]
I think you forgot to make the ghcr images public @groundnuty 

``` 
docker pull ghcr.io/groundnuty/k8s-wait-for:v1.6
Error response from daemon: Head "https://ghcr.io/v2/groundnuty/k8s-wait-for/manifests/v1.6": unauthorized

docker pull ghcr.io/groundnuty/k8s-wait-for:latest
Error response from daemon: Head "https://ghcr.io/v2/groundnuty/k8s-wait-for/manifests/latest": unauthorized
```

**Comment by groundnuty** [comment]
fixed, please check

**Comment by tim-sendible** [comment]
This works now, thanks.

**Comment by andrewcole** [comment]
This is working perfectly for me now, thanks so much @groundnuty!

**Comment by tico24** [comment]
I think you've blocked it again @groundnuty ?

**Comment by groundnuty** [comment]
@tico24 I did not, it's here: https://github.com/groundnuty/k8s-wait-for/pkgs/container/k8s-wait-for
please see if you have access
but for some strange reason it disappeared form the repo landing page, and the 'tick' to enable it ignores my attempts to save it:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/241318/169509259-2da0638c-5fc4-4b86-8c3c-a3bfddb167e2.png">

<img width="620" alt="image" src="https://user-images.githubusercontent.com/241318/169509384-606f84a0-846f-4409-b764-9eeeb5b4a34e.png">

**Comment by tim-sendible** [comment]
it's pulling again now! How odd. Thanks Github!
