### ISSUE TITLE
retried job waited for for ever

### ISSUE THREAD

**Issue by villesau** [groundnuty/k8s-wait-for#53]
If the job first fails and is retried by kubernetes, `k8s-wait-for` is not able to revive from it. It waits for the job for ever even after the retry has succeeded.

**Comment by groundnuty** [comment]
This should address that usecase:
```
Wait for at least one pod in that job to have 'Succeeded' state, does not mind some 'Failed' ones:
wait_for.sh job-wr develop-volume-s3-krakow-init
```

if it does not behave like this, then debugging is needed.

**Comment by villesau** [comment]
Thanks, I'll try that!

**Comment by groundnuty** [comment]
@villesau did you have a chance to check it? If it works as intended please close this issue.

**Comment by villesau** [comment]
@groundnuty thanks for the tip, it worked like a charm! 👌
