### ISSUE TITLE
Add non-root version

### ISSUE THREAD

**Issue by alexsteeel** [groundnuty/k8s-wait-for#54]
Is it possible to add a version with non-root user?

**Comment by groundnuty** [comment]
@alexsteeel Sure, I guess it could a default. I can't imagine what could running everything as regular user break (I'm just not sure what are permissions of the token mounted inside tho).

I don't have a proper secure k8s cluster on my hands to test it properly. So fell free to create a PR that with the modifications that would satisfy your use-case.

**Comment by alexsteeel** [comment]
@groundnuty I added pull-request #55, but I haven't worked with travis, so I'm not sure about my solution.
I checked docker image on my local kubernetes cluster with
```
  securityContext:
	runAsNonRoot: true
```
in deployment for init container. It works.

**Comment by alexsteeel** [comment]
~~I tested with curl without version, not curl=7.80.0-r1. With curl=7.80.0-r1 I have error as in [CI job](https://app.travis-ci.com/github/groundnuty/k8s-wait-for/jobs/575989950).~~

Update: I changed version from 7.80.0-r1 to 7.80.0-r2, it's ok.

**Comment by alexsteeel** [comment]
> I tested with curl without version, not curl=7.80.0-r1. With curl=7.80.0-r1 I have error as in [CI job](https://app.travis-ci.com/github/groundnuty/k8s-wait-for/jobs/575989950).

I changed version from 7.80.0-r1 to 7.80.0-r2,  it's ok.

**Comment by groundnuty** [comment]
@alexsteeel in the end duplication of Dockerfile did not sit well with me I refactored it in 6d103dc I hope it still fulfils your usecase

**Comment by alexsteeel** [comment]
@groundnuty ok, thank you!
