### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by bartwitkowski** [groundnuty/k8s-wait-for#61]
Hi,

How can I debug initContainer with k8s-wait-for?
I only see sth like this:
```
Waiting for pod -lapp=xxxx...
Waiting for pod -lapp=xxxx...
Waiting for pod -lapp=xxxx...
```
Is there any debug swtich?

**Comment by groundnuty** [comment]
Well, exec into it like to any other container in the pod and run the
command you are debugging parallel to the command that is running as an
entry-point.

**Comment by bartwitkowski** [comment]
@groundnuty well yesssss, but running the same command from inside the container gives me the same output. No additional info.
What I did now, is to run `kubectl get pods -o go-template='...'` from your script, and it gives me:
```
I1024 09:27:08.315523   27218 request.go:668] Waited for 1.14891021s due to client-side throttling, not priority and fairness, request: GET:https://xxxx
ReadyReady
```
And it happens all the time the same way: one client-side throttling and one `ReadyReady`.

Running this command from external machine (jumphost) always ends with `ReadyReady`, without client-side throttling.

So, may it be that running from the pod is wrongly parsed?

**Comment by bartwitkowski** [comment]
Looks like it was a problem with kubectl version inside k8s-wait-for container in version 1.5.1
We have K8S version 1.23 but the kubectl was in version 1.21.....
Bumping to 1.6 looks like solving the problem.
If we encounter any problems I will reopen this question.
