### ISSUE TITLE
consider enabling ghcr on the repo and releasing the image there as well

### ISSUE THREAD

**Issue by mmerickel** [groundnuty/k8s-wait-for#62]
Docker Hub throttles traffic and for a critical init container it'd be nice if there were an alternative that was more stable. I'm working around the issue in other ways (re-hosting the image) but just throwing it out there as a suggested improvement.

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by groundnuty** [comment]
We are already using ghrc parallelly to docker hub and actually advertise the usge of ghrc in README.

**Comment by mmerickel** [comment]
Oops I have no idea why I couldn’t find it the other day but sorry for the noise. Must have been rushing too quick.
