### ISSUE TITLE
Namespaces other than default 

### ISSUE THREAD

**Issue by Philippe-Collignon** [groundnuty/k8s-wait-for#9]
The script does not seem to find pods or services in other namespaces ..
Adding --all-namespaces to the kubectl commands in the script solve the issue.

**Comment by groundnuty** [comment]
It does, indirectly.
For example ```k8s-wait-for-.sh job develop-volume-s3-krakow-init -n otherNamespace```.
You can append any kubectl flags to the end. 
It's not a use case I ever tried. Feel free to test it and provide feedback :-)

**Comment by Philippe-Collignon** [comment]
Thanks .. I missed this !
And to look in all namespace, which flag could be used ?

By the way great script ...  thanks

**Comment by groundnuty** [comment]
I would do something like: ```k8s-wait-for-.sh job develop-volume-s3-krakow-init --all-namespaces```
Again, if you could check it and provide feedback - I'm happy to fix any problems that might occure.

**Comment by Philippe-Collignon** [comment]
I've tested, they both work.  Thanks.
